"""Bank I/O for the egm-data stack.

ClassifierBank is the unified in-memory data structure every consumer
agrees on. Source-specific HDF5 banks (synthetic, IAFDB) are read into
the Pydantic models generated by ``myocard-egm-contracts`` and then
converted into ClassifierBank via the converters in :mod:`.converters`.

Public surface:

- :class:`ClassifierBank`, :class:`ClassifierTrace`,
  :class:`ClassifierBankMetaData`, :class:`ClassifierPrediction` — the
  unified types.
- :func:`load_synthetic_bank_as_classifier`,
  :func:`load_iafdb_bank_as_classifier` — convenience: HDF5 path ->
  ClassifierBank in one call.
- :func:`synthetic_bank_to_classifier`,
  :func:`iafdb_bank_to_classifier` — converters taking already-read
  Pydantic models.
- :func:`read_synthetic_bank_hdf5`, :func:`read_iafdb_bank_hdf5`,
  :func:`read_noise_bank_hdf5` — HDF5 -> Pydantic source bank.
- :func:`write_synthetic_bank`, :func:`write_iafdb_bank`,
  :func:`write_noise_bank` — writers for the source-bank formats
  (used by the producer pipelines).
- :func:`write_classifier_bank`, :func:`load_classifier_bank` — HDF5
  I/O for ClassifierBank itself.

The noise_bank format is intentionally minimal — it carries only what
the synthetic mixer consumes. The extraction-provenance sidecar
(noise_bank_run_record JSON) is handled by
:mod:`myocard_egm_data.records.noise_bank_run_record`.
"""

from __future__ import annotations

from .classifier_bank import (
    CLASSIFIER_BANK_VERSION,
    ClassifierBank,
    ClassifierBankMetaData,
    ClassifierPrediction,
    ClassifierTrace,
)
from .classifier_bank_io import load_classifier_bank, write_classifier_bank
from .converters import (
    IAFDBLabelFn,
    LabelResult,
    SyntheticLabelFn,
    iafdb_bank_to_classifier,
    load_iafdb_bank_as_classifier,
    load_synthetic_bank_as_classifier,
    synthetic_bank_to_classifier,
)
from .id_consistency import (
    check_classifier_bank_id_matches_content,
    check_noise_bank_id_agreement,
    check_noise_bank_pair,
)
from .joins import (
    SimulationConfig,
    TraceWithSimulation,
    join_traces_with_simulations,
    simulation_configs,
)
from .noise_bank import read_noise_bank_hdf5, write_noise_bank
from .readers import read_iafdb_bank_hdf5, read_synthetic_bank_hdf5
from .writers import (
    write_iafdb_bank,
    write_synthetic_bank,
)

__all__ = [
    "CLASSIFIER_BANK_VERSION",
    "ClassifierBank",
    "ClassifierBankMetaData",
    "ClassifierPrediction",
    "ClassifierTrace",
    "IAFDBLabelFn",
    "LabelResult",
    "SimulationConfig",
    "SyntheticLabelFn",
    "TraceWithSimulation",
    "check_classifier_bank_id_matches_content",
    "check_noise_bank_id_agreement",
    "check_noise_bank_pair",
    "iafdb_bank_to_classifier",
    "join_traces_with_simulations",
    "load_classifier_bank",
    "load_iafdb_bank_as_classifier",
    "load_synthetic_bank_as_classifier",
    "read_iafdb_bank_hdf5",
    "read_noise_bank_hdf5",
    "read_synthetic_bank_hdf5",
    "simulation_configs",
    "synthetic_bank_to_classifier",
    "write_classifier_bank",
    "write_iafdb_bank",
    "write_noise_bank",
    "write_synthetic_bank",
]
