"""Read source banks (synthetic, IAFDB) from HDF5 into the Pydantic models
generated by ``myocard-egm-contracts``.

These readers do NOT produce ClassifierBank. They produce the typed
Pydantic model that mirrors the JSON Schema, which the consumer then
hands to a converter (``banks/converters.py``) to obtain a
ClassifierBank. The two-step split keeps the read logic (HDF5 →
schema-shaped object) and the conversion logic (schema-shaped object →
classifier-ready data) honest about their boundaries.

For most consumers the right entry point is the
``load_*_as_classifier`` convenience in :mod:`.converters`, which does
both steps in one call.

Performance note: the JSON-Schema codegen models declare per-trace
columns as ``list[list[float]]``, so the bulk arrays round-trip through
Python lists rather than numpy. For Phase-1 bank sizes this is fine; if
we ever scale up significantly a faster reader path (HDF5 → numpy →
ClassifierBank, skipping the Pydantic intermediate) can be added without
changing the public API.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import h5py
import numpy as np
from myocard_egm_contracts import iafdb_bank as _iafdb_bank_models
from myocard_egm_contracts import synthetic_bank as _synthetic_bank_models
from myocard_egm_contracts.schema_info import supported_versions

__all__ = [
    "read_iafdb_bank_hdf5",
    "read_synthetic_bank_hdf5",
]

BANK_TRACES_GROUP = "traces"
SIGNAL_DATASET = "signal"


# ---------------------------------------------------------------------------
# Synthetic bank
# ---------------------------------------------------------------------------


def read_synthetic_bank_hdf5(
    path: Path | str,
) -> _synthetic_bank_models.SyntheticBank:
    """Read a synthetic-bank HDF5 file into a Pydantic SyntheticBank.

    The four JSON-encoded sub-config root attrs
    (``fibrosis_params_json`` etc.) are decoded back to dicts and
    rewritten under the schema-side field names (``fibrosis_params``
    etc.) before constructing the model.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Bank file not found: {path}")
    with h5py.File(path, "r") as f:
        _check_version(f, path, "synthetic_bank")
        if BANK_TRACES_GROUP not in f:
            raise ValueError(f"Bank {path} has no '{BANK_TRACES_GROUP}' group.")

        # Bank-level root attrs.
        doc: dict[str, Any] = {
            "schema_version": _str_attr(f, "schema_version", required=True, path=path),
            "created_utc": _str_attr(f, "created_utc", required=True, path=path),
            "description": _str_attr(f, "description", required=False, path=path, default=""),
            "fs_hz": _float_attr(f, "fs_hz", required=True, path=path),
            "trace_duration_ms": _float_attr(f, "trace_duration_ms", required=True, path=path),
            "simulator": _str_attr(f, "simulator", required=True, path=path),
            "cell_model": _str_attr(f, "cell_model", required=True, path=path),
            "patch_size_mm": _float_attr(f, "patch_size_mm", required=True, path=path),
            "patch_dr_mm": _float_attr(f, "patch_dr_mm", required=True, path=path),
            "ap_time_unit_ms": _float_attr(f, "ap_time_unit_ms", required=True, path=path),
            "fibrosis_strategy_name": _str_attr(
                f, "fibrosis_strategy_name", required=True, path=path
            ),
            "fibrosis_params": _json_attr(f, "fibrosis_params_json"),
            "electrode_config": _json_attr(f, "electrode_config_json"),
            "mixer_config": _json_attr(f, "mixer_config_json"),
            "experiment_config": _json_attr(f, "experiment_config_json"),
            "noise_bank_source": _str_attr(
                f, "noise_bank_source", required=False, path=path, default=""
            ),
        }

        # Per-trace columns.
        g = f[BANK_TRACES_GROUP]
        if SIGNAL_DATASET not in g:
            raise ValueError(f"Bank {path} missing '{BANK_TRACES_GROUP}/{SIGNAL_DATASET}'.")

        signal = np.asarray(g[SIGNAL_DATASET][...], dtype=np.float32)
        # Pydantic codegen emits list[list[float]] for the signal field.
        doc["traces"] = {
            "signal": signal.tolist(),
            "simulation_id": [int(x) for x in g["simulation_id"][...]],
            "pair_index": [int(x) for x in g["pair_index"][...]],
            "electrode_row": [int(x) for x in g["electrode_row"][...]],
            "fibrosis_density": [float(x) for x in g["fibrosis_density"][...]],
            "fibrosis_density_realized": [float(x) for x in g["fibrosis_density_realized"][...]],
            "electrode_height_mm": [float(x) for x in g["electrode_height_mm"][...]],
            "seed": [int(x) for x in g["seed"][...]],
            "snr_db": [float(x) for x in g["snr_db"][...]],
            "stim_edge": [_decode(x) for x in g["stim_edge"][...]],
            "noise_record": [_decode(x) for x in g["noise_record"][...]],
            "noise_channel": [_decode(x) for x in g["noise_channel"][...]],
        }

    return _synthetic_bank_models.SyntheticBank.model_validate(doc)


# ---------------------------------------------------------------------------
# IAFDB bank
# ---------------------------------------------------------------------------


def read_iafdb_bank_hdf5(path: Path | str) -> _iafdb_bank_models.IafdbBank:
    """Read an IAFDB-bank HDF5 file into a Pydantic IafdbBank.

    The IAFDB bank carries no labels (per v0.1.2 of egm-contracts):
    labeling is consumer-side policy applied at ClassifierBank
    conversion time via a ``label_fn``.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Bank file not found: {path}")
    with h5py.File(path, "r") as f:
        _check_version(f, path, "iafdb_bank")
        if BANK_TRACES_GROUP not in f:
            raise ValueError(f"Bank {path} has no '{BANK_TRACES_GROUP}' group.")

        doc: dict[str, Any] = {
            "schema_version": _str_attr(f, "schema_version", required=True, path=path),
            "created_utc": _str_attr(f, "created_utc", required=True, path=path),
            "source": _str_attr(f, "source", required=True, path=path),
            "fs_hz": _float_attr(f, "fs_hz", required=True, path=path),
            "trace_duration_ms": _float_attr(f, "trace_duration_ms", required=True, path=path),
            "calibration_method": _str_attr(f, "calibration_method", required=True, path=path),
            "calibration_target_qrs_pp_mv": _float_attr(
                f, "calibration_target_qrs_pp_mv", required=True, path=path
            ),
            "threshold_mode": _str_attr(f, "threshold_mode", required=True, path=path),
            "threshold_value": _float_attr(f, "threshold_value", required=True, path=path),
            "band_hz": [float(x) for x in np.asarray(f.attrs["band_hz"])],
            "window_ms": _float_attr(f, "window_ms", required=True, path=path),
            "window_samples": int(f.attrs["window_samples"]),
            "hop_ms": _float_attr(f, "hop_ms", required=True, path=path),
            "source_records": [_decode(x) for x in np.asarray(f.attrs.get("source_records", []))],
        }

        g = f[BANK_TRACES_GROUP]
        if SIGNAL_DATASET not in g:
            raise ValueError(f"Bank {path} missing '{BANK_TRACES_GROUP}/{SIGNAL_DATASET}'.")

        signal = np.asarray(g[SIGNAL_DATASET][...], dtype=np.float32)
        doc["traces"] = {
            "signal": signal.tolist(),
            "patient_id": [_decode(x) for x in g["patient_id"][...]],
            "source_record": [_decode(x) for x in g["source_record"][...]],
            "source_channel": [_decode(x) for x in g["source_channel"][...]],
            "start_sample": [int(x) for x in g["start_sample"][...]],
            "peak_to_peak_mv": [float(x) for x in g["peak_to_peak_mv"][...]],
            "calibration_scalar": [float(x) for x in g["calibration_scalar"][...]],
        }

    return _iafdb_bank_models.IafdbBank.model_validate(doc)


# ---------------------------------------------------------------------------
# HDF5 attr helpers
# ---------------------------------------------------------------------------


def _check_version(f: h5py.File, path: Path, schema_name: str) -> None:
    raw = f.attrs.get("schema_version", "")
    version = raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)
    supported = supported_versions(schema_name)
    if version not in supported:
        raise ValueError(
            f"Bank {path} has schema_version {version!r}; the installed "
            f"myocard-egm-contracts supports {schema_name} versions {supported}."
        )


def _decode(value: Any) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return str(value)


def _str_attr(
    f: h5py.File,
    name: str,
    *,
    required: bool,
    path: Path,
    default: str = "",
) -> str:
    if name not in f.attrs:
        if required:
            raise ValueError(f"Bank {path} is missing required root attr {name!r}.")
        return default
    raw = f.attrs[name]
    return raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)


def _float_attr(f: h5py.File, name: str, *, required: bool, path: Path) -> float:
    if name not in f.attrs:
        if required:
            raise ValueError(f"Bank {path} is missing required root attr {name!r}.")
        return 0.0
    return float(f.attrs[name])


def _json_attr(f: h5py.File, name: str) -> dict[str, Any]:
    """Decode a JSON-encoded string root attr into a dict (or {} if missing)."""
    if name not in f.attrs:
        return {}
    raw = f.attrs[name]
    text = raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)
    try:
        decoded = json.loads(text) if text else {}
    except json.JSONDecodeError:
        return {}
    return decoded if isinstance(decoded, dict) else {}
