"""Read source banks (synthetic, IAFDB) from HDF5 into the Pydantic models
generated by ``myocard-egm-contracts``.

These readers do NOT produce ClassifierBank. They produce the typed
Pydantic model that mirrors the JSON Schema, which the consumer then
hands to a converter (``banks/converters.py``) to obtain a
ClassifierBank. The two-step split keeps the read logic (HDF5 →
schema-shaped object) and the conversion logic (schema-shaped object →
classifier-ready data) honest about their boundaries.

For most consumers the right entry point is the
``load_*_as_classifier`` convenience in :mod:`.converters`, which does
both steps in one call.

Performance note: the JSON-Schema codegen models declare per-trace
columns as ``list[list[float]]``, so the bulk arrays round-trip through
Python lists rather than numpy. For Phase-1 bank sizes this is fine; if
we ever scale up significantly a faster reader path (HDF5 → numpy →
ClassifierBank, skipping the Pydantic intermediate) can be added without
changing the public API.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import h5py
import numpy as np
from myocard_egm_contracts import iafdb_bank as _iafdb_bank_models
from myocard_egm_contracts import synthetic_bank as _synthetic_bank_models
from myocard_egm_contracts.schema_info import supported_versions

__all__ = [
    "read_iafdb_bank_hdf5",
    "read_synthetic_bank_hdf5",
]

BANK_TRACES_GROUP = "traces"
BANK_SIMULATIONS_GROUP = "simulations"
SIGNAL_DATASET = "signal"

#: Per-simulation config columns stored as JSON strings in ``simulations/``.
#: HDF5 has no nested-record type worth using and these objects are
#: polymorphic (a ``substrate`` may be uniform-random today and patchy
#: tomorrow), so each row is a JSON document under a ``_json``-suffixed
#: dataset. The schema describes the *decoded* form under the unsuffixed
#: name — the same convention the contracts validator's
#: ``_hdf5.read_json_columns`` implements on its side.
SIMULATION_JSON_COLUMNS = (
    "geometry",
    "cell_model",
    "substrate",
    "substrate_summary",
    "activation",
    "electrodes",
    "backend",
    "label_policy",
    "label_names",
)

#: Plain integer columns in ``simulations/``.
SIMULATION_INT_COLUMNS = ("simulation_id", "seed")


# ---------------------------------------------------------------------------
# Synthetic bank
# ---------------------------------------------------------------------------


def read_synthetic_bank_hdf5(
    path: Path | str,
) -> _synthetic_bank_models.SyntheticBank:
    """Read a synthetic-bank HDF5 file into a Pydantic SyntheticBank.

    Reads the schema-2.0 layout: bank-scoped root attrs (including the
    JSON-encoded ``generation_params_json`` θ-spec), a ``simulations/``
    group holding one typed, polymorphic config object per simulation,
    and a collapsed ``traces/`` group of signal + two foreign keys +
    label + noise provenance.

    **No 1.1 compatibility.** A pre-2.0 bank is refused by the version
    check rather than partially read: the generation parameters it
    carries live in columns that no longer exist, so a "best effort"
    read would silently drop the very provenance the bank exists to
    record. Regenerate instead — nothing released depends on a 1.1 bank
    (egm-contracts v0.6.0 CHANGELOG).
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Bank file not found: {path}")
    with h5py.File(path, "r") as f:
        _check_version(f, path, "synthetic_bank")
        for group in (BANK_SIMULATIONS_GROUP, BANK_TRACES_GROUP):
            if group not in f:
                raise ValueError(f"Bank {path} has no '{group}' group.")

        # Bank-level root attrs. generation_params is the sweep-scoped
        # θ-spec, JSON-encoded because it is a nested object.
        doc: dict[str, Any] = {
            "schema_version": _str_attr(f, "schema_version", required=True, path=path),
            "created_utc": _str_attr(f, "created_utc", required=True, path=path),
            "bank_id": _opt_str_attr(f, "bank_id"),
            "description": _str_attr(f, "description", required=False, path=path, default=""),
            "fs_hz": _float_attr(f, "fs_hz", required=True, path=path),
            "trace_duration_ms": _float_attr(f, "trace_duration_ms", required=True, path=path),
            "noise_bank_source": _str_attr(
                f, "noise_bank_source", required=False, path=path, default=""
            ),
            "generation_params": _json_attr(f, "generation_params_json"),
        }

        doc["simulations"] = _read_simulations_group(f[BANK_SIMULATIONS_GROUP], path=path)
        doc["traces"] = _read_synthetic_traces_group(f[BANK_TRACES_GROUP], path=path)

    return _synthetic_bank_models.SyntheticBank.model_validate(doc)


def _read_simulations_group(g: h5py.Group, *, path: Path) -> dict[str, Any]:
    """Decode the ``simulations/`` group into schema shape.

    Each ``<name>_json`` dataset holds one JSON document per simulation;
    they are decoded and re-keyed to the unsuffixed name the schema
    describes. A row that fails to parse is deliberately **not** left as
    a raw string here (unlike the contracts validator, which does that so
    it can report a useful schema error): this reader's caller gets a
    Pydantic model or an exception, so a malformed row must fail loudly
    with the column and row that caused it.
    """
    out: dict[str, Any] = {}
    for name in SIMULATION_INT_COLUMNS:
        if name not in g:
            raise ValueError(f"Bank {path} missing '{BANK_SIMULATIONS_GROUP}/{name}'.")
        out[name] = [int(x) for x in g[name][...]]

    for name in SIMULATION_JSON_COLUMNS:
        dataset = f"{name}_json"
        if dataset not in g:
            raise ValueError(f"Bank {path} missing '{BANK_SIMULATIONS_GROUP}/{dataset}'.")
        decoded: list[Any] = []
        for row, raw in enumerate(g[dataset][...]):
            text = _decode(raw)
            try:
                decoded.append(json.loads(text))
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Bank {path}: '{BANK_SIMULATIONS_GROUP}/{dataset}' row {row} is not "
                    f"valid JSON ({exc}). Each row holds one typed config object."
                ) from exc
        out[name] = decoded
    return out


def _read_synthetic_traces_group(g: h5py.Group, *, path: Path) -> dict[str, Any]:
    """Decode the collapsed 2.0 ``traces/`` group into schema shape."""
    if SIGNAL_DATASET not in g:
        raise ValueError(f"Bank {path} missing '{BANK_TRACES_GROUP}/{SIGNAL_DATASET}'.")

    signal = np.asarray(g[SIGNAL_DATASET][...], dtype=np.float32)
    # Pydantic codegen emits list[list[float]] for the signal field.
    traces: dict[str, Any] = {
        "signal": signal.tolist(),
        "simulation_id": [int(x) for x in g["simulation_id"][...]],
        "pair_index": [int(x) for x in g["pair_index"][...]],
        "label": [int(x) for x in g["label"][...]],
        "snr_db": [float(x) for x in g["snr_db"][...]],
        "noise_record": [_decode(x) for x in g["noise_record"][...]],
        "noise_channel": [_decode(x) for x in g["noise_channel"][...]],
    }
    # Optional and permanently so — present only once SEP2 anchors the
    # crop. Left unset rather than zero-filled: absence means "unknown
    # position", while a zero would read as "activation at the very
    # start of the trace". Mirrors the iafdb_bank column exactly.
    if "activation_position" in g:
        traces["activation_position"] = [float(x) for x in g["activation_position"][...]]
    return traces


# ---------------------------------------------------------------------------
# IAFDB bank
# ---------------------------------------------------------------------------


def read_iafdb_bank_hdf5(path: Path | str) -> _iafdb_bank_models.IafdbBank:
    """Read an IAFDB-bank HDF5 file into a Pydantic IafdbBank.

    The IAFDB bank carries no labels (per v0.1.2 of egm-contracts):
    labeling is consumer-side policy applied at ClassifierBank
    conversion time via a ``label_fn``.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Bank file not found: {path}")
    with h5py.File(path, "r") as f:
        _check_version(f, path, "iafdb_bank")
        if BANK_TRACES_GROUP not in f:
            raise ValueError(f"Bank {path} has no '{BANK_TRACES_GROUP}' group.")

        doc: dict[str, Any] = {
            "schema_version": _str_attr(f, "schema_version", required=True, path=path),
            "created_utc": _str_attr(f, "created_utc", required=True, path=path),
            "bank_id": _opt_str_attr(f, "bank_id"),
            # iafdb_bank 1.3 (B11): absence means "no sidecar", not an error.
            "run_record_path": _opt_str_attr(f, "run_record_path"),
            "source": _str_attr(f, "source", required=True, path=path),
            "fs_hz": _float_attr(f, "fs_hz", required=True, path=path),
            "trace_duration_ms": _float_attr(f, "trace_duration_ms", required=True, path=path),
            "calibration_method": _str_attr(f, "calibration_method", required=True, path=path),
            "calibration_target_qrs_pp_mv": _float_attr(
                f, "calibration_target_qrs_pp_mv", required=True, path=path
            ),
            "threshold_mode": _str_attr(f, "threshold_mode", required=True, path=path),
            "threshold_value": _float_attr(f, "threshold_value", required=True, path=path),
            "band_hz": [float(x) for x in np.asarray(f.attrs["band_hz"])],
            "window_ms": _float_attr(f, "window_ms", required=True, path=path),
            "window_samples": int(f.attrs["window_samples"]),
            "hop_ms": _float_attr(f, "hop_ms", required=True, path=path),
            "source_records": [_decode(x) for x in np.asarray(f.attrs.get("source_records", []))],
        }

        g = f[BANK_TRACES_GROUP]
        if SIGNAL_DATASET not in g:
            raise ValueError(f"Bank {path} missing '{BANK_TRACES_GROUP}/{SIGNAL_DATASET}'.")

        signal = np.asarray(g[SIGNAL_DATASET][...], dtype=np.float32)
        doc["traces"] = {
            "signal": signal.tolist(),
            "patient_id": [_decode(x) for x in g["patient_id"][...]],
            "source_record": [_decode(x) for x in g["source_record"][...]],
            "source_channel": [_decode(x) for x in g["source_channel"][...]],
            "start_sample": [int(x) for x in g["start_sample"][...]],
            "peak_to_peak_mv": [float(x) for x in g["peak_to_peak_mv"][...]],
            "calibration_scalar": [float(x) for x in g["calibration_scalar"][...]],
        }
        # iafdb_bank 1.3: optional and permanently so — present only on
        # activation-split banks. Left unset (not zero-filled) when absent,
        # because the schema requires readers to treat absence as "unknown
        # position"; a zeroed column would read as "every activation sits at
        # the very start of its window".
        if "activation_position" in g:
            doc["traces"]["activation_position"] = [float(x) for x in g["activation_position"][...]]

    return _iafdb_bank_models.IafdbBank.model_validate(doc)


# ---------------------------------------------------------------------------
# HDF5 attr helpers
# ---------------------------------------------------------------------------


def _check_version(f: h5py.File, path: Path, schema_name: str) -> None:
    raw = f.attrs.get("schema_version", "")
    version = raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)
    supported = supported_versions(schema_name)
    if version not in supported:
        raise ValueError(
            f"Bank {path} has schema_version {version!r}; the installed "
            f"myocard-egm-contracts supports {schema_name} versions {supported}."
        )


def _decode(value: Any) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return str(value)


def _str_attr(
    f: h5py.File,
    name: str,
    *,
    required: bool,
    path: Path,
    default: str = "",
) -> str:
    if name not in f.attrs:
        if required:
            raise ValueError(f"Bank {path} is missing required root attr {name!r}.")
        return default
    raw = f.attrs[name]
    return raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)


def _opt_str_attr(f: h5py.File, name: str) -> str | None:
    """Read an optional string root attr, returning ``None`` when absent.

    Distinct from ``_str_attr(..., required=False)`` which returns ``""``:
    an absent optional id must be ``None`` (so the Pydantic model leaves it
    unset), never ``""`` (which would fail the stable-id pattern).
    """
    if name not in f.attrs:
        return None
    raw = f.attrs[name]
    return raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)


def _float_attr(f: h5py.File, name: str, *, required: bool, path: Path) -> float:
    if name not in f.attrs:
        if required:
            raise ValueError(f"Bank {path} is missing required root attr {name!r}.")
        return 0.0
    return float(f.attrs[name])


def _json_attr(f: h5py.File, name: str) -> dict[str, Any]:
    """Decode a JSON-encoded string root attr into a dict (or {} if missing)."""
    if name not in f.attrs:
        return {}
    raw = f.attrs[name]
    text = raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)
    try:
        decoded = json.loads(text) if text else {}
    except json.JSONDecodeError:
        return {}
    return decoded if isinstance(decoded, dict) else {}
